version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=auto_socials
      - DB_POSTGRESDB_USER=auto_socials
      - DB_POSTGRESDB_PASSWORD=auto_socials_password
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecretpassword
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - ./n8n_data:/home/node/.n8n
